server:
  port: 8081
  servlet:
    context-path: /joole

limit:
  minMoney: 0.01
  maxMoney: 9999
  description: at least ${limit.minMoney}dollars, max is ${limit.maxMoney}dollars

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/joole?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: adminadmin
  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect