server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 0.01
  maxMoney: 9999
  description: at least ${limit.minMoney}dollars, max is ${limit.maxMoney}dollars

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jooleprojectdatabase
    username: root
    password: Cavalcante10@hl
  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect